version: "3.8"
services:
  api:
    container_name: pdf_paragraphs_extraction_api
    entrypoint: [ "gunicorn", "-k", "uvicorn.workers.UvicornWorker", "--chdir", "./src", "app:app", "--bind", "0.0.0.0:5051" ]
    init: true
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - data:/app/docker_volume
    depends_on:
      - mongo_paragraphs
      - redis_paragraphs
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - SENTRY_DSN=${SENTRY_DSN:-}
      - WEB_CONCURRENCY=2
    networks:
      - pdf_paragraphs_extraction_network
    ports:
      - "5051:5051"
    env_file: .env
  extract_pdf_paragraphs:
    container_name: pdf_paragraphs_extraction_worker
    entrypoint: [ "python", "-m", "src.QueueProcessor" ]
    init: true
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - data:/app/docker_volume
    depends_on:
      - mongo_paragraphs
      - redis_paragraphs
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - SENTRY_DSN=${SENTRY_DSN:-}
    networks:
      - pdf_paragraphs_extraction_network
    env_file: .env
  mongo_paragraphs:
    restart: unless-stopped
    command: mongod --port 28017
    image: "mongo:4.0.1"
    networks:
      - pdf_paragraphs_extraction_network
  redis_paragraphs:
    restart: unless-stopped
    image: "redis:5.0.14"
    command: redis-server
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - pdf_paragraphs_extraction_network
    ports:
      - "6379:6379"
networks:
  pdf_paragraphs_extraction_network:

volumes:
  data: